POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"admin",
    "password":"123"
    
}
###
GET http://localhost:3000
Content-Type: application/json
Authorization: Bearer token

{
    
}
###
GET http://localhost:3000/0
Content-Type: application/json
Authorization: Bearer token

{
    
}
###
POST  http://localhost:3000
Content-Type: application/json
Authorization: Bearer token

{
    "username":"fulano de tal",
    "password":12355
}
###
DELETE http://localhost:3000/0
Content-Type: application/json
Authorization: Bearer token

###
PUT  http://localhost:3000/0
Content-Type: application/json
Authorization: Bearer token

{
    "username":"fulano de tal de logo alí",
    "password":321
}